name: mlprojects
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - matplotlib=3.7.2
  - numpy=1.25.2
  - scikit-learn=1.3.0
  - pip=23.2.1
  - pip:
      - nvidia-pyindex
      - tritonclient[all]
